Partial Sandbox/force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <label>Inhabitant</label>
    <nameField>
        <label>Inhabitant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial Sandbox/force-app/main/default/objects/Inhabitant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Inhabitants</relationshipLabel>
    <relationshipName>Inhabitants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial Sandbox/force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial Sandbox/force-app/main/default/objects/Package__c/fields/Inhabitant__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inhabitant</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial Sandbox/force-app/main/default/objects/Package__c/fields/Shipping_Status__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Status__c</fullName>
    <label>Shipping Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for Pickup</fullName>
                <default>true</default>
                <label>Waiting for Pickup</label>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial Sandbox/force-app/main/default/objects/Package__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <description>A randomly generated tracking number which resists any guessing attempts for security purposes.</description>
    <label>Tracking Number</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Partial Sandbox/force-app/main/default/classes/MissionViewBoardController.cls
public class MissionViewBoardController 
{
    /*** Properties ***/
    public User currentUser {get; set;}
    public Contact userContact {get; set;}
    public Account userAccount {get; set;}  
    public String trackingNumber {get; set;}
    String error {get; set;}
    List<SelectOption> options {get; set;}
    List<Inhabitant__c> residents {get; set;}
    public PageReference editAccount{get
    {
        if(editAccount == null)
        {
            if(userAccount != null)
        	{
            	//editAccount = new ApexPages.StandardController(userAccount).edit();
                editAccount = new PageReference(URL.getSalesforceBaseUrl().toExternalForm() + '/apex/FindEditAccountInfo?id=' +  userAccount.Id);
        	}
       	 	else
        	{
            	editAccount = ApexPages.currentPage();
        	}         
        }
        return editAccount;
    }set;}
    public String status {get; set;}
    public List<Package__c> packages {get
    {
        if(packages == null && userContact != null) 
        {
            residents = [SELECT Id, Contact__r.Id 
                         FROM Inhabitant__c 
                         WHERE Contact__r.Id =: userContact.Id];
            packages = [SELECT Shipping_Status__c, Tracking_Number__c 
                        FROM Package__c 
                        WHERE Inhabitant__r.Id IN :residents];
        }
        return packages;
    }set;}
	/*** Constructors ***/
	public MissionViewBoardController()
    {           
        try
        {
          currentUser = [SELECT ID, ContactId FROM User WHERE Id =: UserInfo.getUserId()];  
          userContact = [SELECT Account.Name, AccountId, FirstName, LastName 
                         FROM Contact 
                         WHERE Id =: currentUser.ContactId]; 
            
           if(userContact.AccountId != null )
           {
                userAccount = new Account(Id = userContact.AccountId, Name = userContact.Account.Name); 
           }
        }
        catch(System.QueryException e)
        {
            userContact = null;
			error = e.getMessage();            
        } 
    }
    //Action method to display our statuses on the MissionViewBoard visualforcepage. 
    public List<SelectOption> getItems()
    {
        options = new List<SelectOption>{new SelectOption('All', 'All'), new SelectOption('Shipping', 'Shipping'), new SelectOption('Delivered', 'Delivered')};
        return options;
    }
    //Action method for allowing filtering of packages by status on the 
    //MissionViewBoard visualforcepage.
    public void setPackages()
    {
        List<String> statuses;
        switch on status {
            when 'All' {statuses = new List<String>{'Missing', 'Delivered', 'Out for Delivery', 'In Transit', 'Waiting for Pickup'};}
            when 'Shipping' {statuses = new List<String>{'Out for Delivery', 'In Transit', 'Waiting for Pickup'};}
            when 'Delivered' {statuses = new List<String>{'Delivered'};}
        }
        packages = [SELECT Shipping_Status__c, Tracking_Number__c FROM Package__c 
                    WHERE (Inhabitant__r.Id IN :residents) AND Shipping_Status__c IN :statuses LIMIT 20];
    }    
}