Partial Sandbox/force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial Sandbox/force-app/main/default/objects/Package__c/fields/Shipping_Status__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Status__c</fullName>
    <label>Shipping Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for Pickup</fullName>
                <default>true</default>
                <label>Waiting for Pickup</label>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial Sandbox/force-app/main/default/classes/PastList.cls
public class PastList {
    private ApexPages.StandardSetController ssc;

    public PastList()
    {
        List<Package__c> PackageList = [SELECT Name, Shipping_Status__c FROM Package__c];

        ssc = new ApexPages.StandardSetController(PackageList);
        ssc.setFilterID('00B17000004Gxe8');
    }

    public List<Package__c> getPackages() 
    {
        return (List<Package__c>)ssc.getRecords();
    }
}