Partial Sandbox/force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial Sandbox/force-app/main/default/objects/Package__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <description>A randomly generated tracking number which resists any guessing attempts for security purposes.</description>
    <label>Tracking Number</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Partial Sandbox/force-app/main/default/classes/Tracking.cls
public class Tracking {
        public static void createTrackingNumbers(Package__c[] newPackages) {
            Package__c[] trackedPackages = new List<Package__c>();
            for (Integer i = 0; i < newPackages.size(); i++)
                trackedPackages.add([SELECT Name FROM Package__c WHERE Id =: newPackages[i].Id LIMIT 1]);
            for (Integer i = 0; i < trackedPackages.size(); i++)
                trackedPackages[i].Tracking_Number__c = EncodingUtil.convertToHex(
                    Crypto.generateDigest('SHA1',Blob.valueOf(trackedPackages[i].Name)));
            update trackedPackages;
        }
}