Partial Sandbox/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Street</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial Sandbox/force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City of the address.</description>
    <inlineHelpText>Enter the City name of the address.</inlineHelpText>
    <label>City</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Partial Sandbox/force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State of the address.</description>
    <inlineHelpText>Enter a two letter description of the state of the address.</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Partial Sandbox/force-app/main/default/objects/Address__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>The Zip/Postal code of the address.</description>
    <inlineHelpText>Enter the Zip/Postal code of the address.</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Partial Sandbox/force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <label>Inhabitant</label>
    <nameField>
        <label>Inhabitant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial Sandbox/force-app/main/default/objects/Inhabitant__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Inhabitants</relationshipLabel>
    <relationshipName>Inhabitants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial Sandbox/force-app/main/default/objects/Inhabitant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Inhabitants</relationshipLabel>
    <relationshipName>Inhabitants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial Sandbox/force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial Sandbox/force-app/main/default/objects/Package__c/fields/Inhabitant__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inhabitant</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial Sandbox/force-app/main/default/objects/Package__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <description>A randomly generated tracking number which resists any guessing attempts for security purposes.</description>
    <label>Tracking Number</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Partial Sandbox/force-app/main/default/classes/testTracking.cls
@isTest
public class testTracking {
    	@isTest
    	public static void testTrackingTest(){
    		Contact cont = new Contact(LastName='Saruman');
    		Address__c addr = new Address__c( Name = '1120 Boolean Road',
                                     City__c='Moscow', State__c='Idaho', 
                                     Zip_Code__c = '99163');
    		insert cont;
    		insert addr;
    		cont = [SELECT Id FROM contact WHERE LastName='Saruman'];
    		addr = [SELECT Id FROM address__c WHERE Name = '1120 Boolean Road'];
    		Inhabitant__c inhab = new Inhabitant__c(Name = 'Castle', 
                                                Address__c = addr.Id, 
                                                Contact__c = cont.Id);
            insert inhab;
            inhab = [SELECT Id FROM Inhabitant__c WHERE Name = 'Castle'];
            Package__c pack = new Package__c(Inhabitant__c = inhab.id);
            insert pack;
            pack = [SELECT Name, Tracking_Number__c FROM Package__c LIMIT 1];
            String tracking = pack.Tracking_Number__c;
            Package__c testpack = [SELECT Name FROM Package__c WHERE Tracking_Number__c = :tracking];
            system.assertEquals(pack.Name, testpack.Name);
    }
}